### PR TITLE
Add docker-compose config, with profiles for sqlite and couchdb

### PR DESCRIPTION
**Pull request by scottaubrey**
Added documentation, ~but not added Makefile targets (yet).~ Will added make targets

This should bring up either a CouchDB, or SQLite ~+ minio (s3) replicated app locally,~ fully configured and setup.

The data will persist between `docker-compose up` runs (via docker anonymous volumes) and instructions for deleting volumes is included.

### CODE REVIEW

**Comment by nlisgo** [comment]
Taking a look at this now

**Comment by nlisgo** [comment]
I get the following error when I run either `make watch-sqlite` or `make watch-couchdb`:

```
ERROR: The Compose file is invalid because:
Service app-sqlite has neither an image nor a build context specified. At least one must be provided.
make: *** [watch-sqlite] Error 1
```

**Comment by nlisgo** [comment]
Similar error if I run `docker-compose --profile sqlite up -d` or `docker-compose --profile couchdb up -d`:

```
ERROR: The Compose file is invalid because:
Service app-sqlite has neither an image nor a build context specified. At least one must be provided.
```

**Review by nlisgo — DISMISSED** [review]
See comments regarding errors.

**Comment by scottaubrey** [comment]
> See comments regarding errors.

@nlisgo  I can only recreate those errors when using docker-compose v1, seems fine with v2. Could you give it a try with a newer docker-compose? (obviously, for the slight issues we discovered with Journal using v2, you'll maybe want to keep v1 around still).

**Comment by will-byrne** [comment]
if i run a `docker-compose -v` i get `docker-compose version 1.29.2, build 5becea4c` so it should run on version 1.

**Comment by scottaubrey** [comment]
> if i run a `docker-compose -v` i get `docker-compose version 1.29.2, build 5becea4c` so it should run on version 1.
> 
> edit: do we need to specify the version at the top of the compose file?

That's... weird. I definitely get it with old docker-compose:

```
> docker-compose-v1 -v
docker-compose version 1.29.2, build 5becea4c

> docker-compose-v1 --profile sqlite up
ERROR: The Compose file is invalid because:
Service app-sqlite has neither an image nor a build context specified. At least one must be provided.

> docker-compose -v
Docker Compose version 2.6.1

> docker-compose --profile sqlite up
[+] Running 0/0
 ⠋ Network enhanced-preprints_default  Creating                                                                                                                                                                                                            0.0s
[+] Running 2/1d orphan containers ([enhanced-preprints-unleash-1 enhanced-preprints-unleash-postgres-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. ⠿ Network enhanced-preprints_default         Created                                                                                                                                                                                                      0.0s
 ⠿ Container enhanced-preprints-app-sqlite-1  Created                                                                                                                                                                                                      0.1s
Attaching to enhanced-preprints-app-sqlite-1
enhanced-preprints-app-sqlite-1  | yarn run v1.22.18
enhanced-preprints-app-sqlite-1  | $ nodemon src/server.ts
enhanced-preprints-app-sqlite-1  | [nodemon] 2.0.18
enhanced-preprints-app-sqlite-1  | [nodemon] to restart at any time, enter `rs`
enhanced-preprints-app-sqlite-1  | [nodemon] watching path(s): *.*
enhanced-preprints-app-sqlite-1  | [nodemon] watching extensions: ts,json
enhanced-preprints-app-sqlite-1  | [nodemon] starting `ts-node src/server.ts`
enhanced-preprints-app-sqlite-1  | Example app listening on port 3000
```

Not sure, but I'd guess somehow it's being run with a v2 @will-byrne ? Or maybe it's only on docker-compose v1 for Mac?

Anyway, I've also pushed up a change which should allow it to work docker-compose v1 on my machine, I'd be interested to hear from @nlisgo if the changes work.

**Review by will-byrne — APPROVED** [review]

**Review by will-byrne — APPROVED** [review]

**Review by will-byrne — APPROVED** [review]

**Pull request merged**
