### PR TITLE
Hardcode editors evaluation summary on article page

### LINKED ISSUE #85: Hard coded Editors Evaluation with key words on the article page
# Description

# Clarification questions

- Is the board supporting this solution?
**Not sure but let's test this solution**

- Do we place it at the top?
**Yes let's test this position**

- Are we still calling them "Editors Evaluations"?  Or is it "Peer Review Summary" now?
**Andy said he’d speak to the editors about the name next week, but for now let’s call it Evaluation Summary**

### How could we measure the impact or benefit of the solution?

# Documents and Resources

- [ ] [Mockup](https://projects.invisionapp.com/share/4Z12PZBKD6WR#/screens/467140916_just-Hyperlinks-Preprint)
- [ ] [Mockup not to be used](https://projects.invisionapp.com/share/4Z12PZBKD6WR#/screens/467140920_hyperlinks-And-Scale-Preprint)
- [ ] [Document 2](https://link.to.the.resource)

# Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] ...

# Definition of Done

- [ ] Solution deployed into a production environment and accessible to users.
- [ ] Solution reviewed and approved by all stakeholders.
- [ ] ...

### PR DESCRIPTION
**Pull request by scottaubrey**
fixes #85

### CODE REVIEW

**Comment by nlisgo** [comment]
Looking at this. Just pulling it down locally.

**Comment by nlisgo** [comment]
Do we have a separate ticket to introduce the editors evaluation to the left nav or should we add it here too?

**Comment by scottaubrey** [comment]
> Do we have a separate ticket to introduce the editors evaluation to the left nav or should we add it here too?

You know, I hadn't thought about that, even as I was doing it. We should do it all in one change I think, though the how will be interesting.

**Comment by scottaubrey** [comment]
> > Do we have a separate ticket to introduce the editors evaluation to the left nav or should we add it here too?
> 
> You know, I hadn't thought about that, even as I was doing it. We should do it all in one change I think, though the how will be interesting.

@nlisgo I've hardcoded both the ID and the ToC list item for it into each function's HTML. I really don't like how coupled these two separate functions are now because of that, but without adding it back into the article body and reparsing the HTML, I couldn't think of a better way to do it right now.

Longer term the ToC probably won't be generated by parsing the HTML in the first place, so it probably won't matter, so I just stuck with it, is that OK?

**Review by will-byrne — APPROVED** [review]

**Pull request merged**
